// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyBkNGX7kKIqph1t_NC0MDQHCGIFDj6W8',
    appId: '1:853546573445:web:adaf29011e26e1dd8853ec',
    messagingSenderId: '853546573445',
    projectId: 'wishes-app-883ff',
    authDomain: 'wishes-app-883ff.firebaseapp.com',
    storageBucket: 'wishes-app-883ff.firebasestorage.app',
    measurementId: 'G-CT1WQRLVEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5GNg5J09KhMWC2zL9Uf_oA3UMzgLJWAI',
    appId: '1:853546573445:android:3182b209083d80a58853ec',
    messagingSenderId: '853546573445',
    projectId: 'wishes-app-883ff',
    storageBucket: 'wishes-app-883ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiHpWif1ayAad7NZFTNGEJNSNB8fj7HoM',
    appId: '1:853546573445:ios:9c1f462bba615cb98853ec',
    messagingSenderId: '853546573445',
    projectId: 'wishes-app-883ff',
    storageBucket: 'wishes-app-883ff.firebasestorage.app',
    iosBundleId: 'com.example.wishesSocialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiHpWif1ayAad7NZFTNGEJNSNB8fj7HoM',
    appId: '1:853546573445:ios:9c1f462bba615cb98853ec',
    messagingSenderId: '853546573445',
    projectId: 'wishes-app-883ff',
    storageBucket: 'wishes-app-883ff.firebasestorage.app',
    iosBundleId: 'com.example.wishesSocialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyBkNGX7kKIqph1t_NC0MDQHCGIFDj6W8',
    appId: '1:853546573445:web:8ff3fe981ef2f4d18853ec',
    messagingSenderId: '853546573445',
    projectId: 'wishes-app-883ff',
    authDomain: 'wishes-app-883ff.firebaseapp.com',
    storageBucket: 'wishes-app-883ff.firebasestorage.app',
    measurementId: 'G-YYBB3TJKJF',
  );

}